// Web Frameworks/Lab1-MangabatAster/lab1-react/src/App.jsx
import { useState } from 'react'
import './App.css'

function App() {
  const [email, setEmail] = useState("");
  const [fName, setFName] = useState("");
  const [lName, setLName] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  const validatePhoneNumber = (phone) => {
    const phonePattern = /^09\d{2}-\d{3}-\d{4}$/;
    return phonePattern.test(phone);
  };

  const handleSubmit = (event) => {
    event.preventDefault(); 

    if (!validatePhoneNumber(phoneNumber)) {
      setErrorMessage("Please follow the format for phone number: 09xx-xxx-xxxx.");
      return;
    }
    setErrorMessage("");

    const userData = {
      email,
      first_name: fName,
      last_name: lName,
      phone_number: phoneNumber
    };

    console.log(userData);
  };

  return (
    <div className="flex items-center justify-center min-h-screen">
      <form onSubmit={handleSubmit} className="w-full max-w-md p-8 rounded-lg border border-black">
        <h1 className="text-3xl font-extrabold text-center mb-6">Form</h1>
        <p className="mb-4">
          <label className="block text-gray-700 text-sm font-bold mb-1" htmlFor="email">
            Email:
          </label>
          <input
            type="email"
            id="email"
            placeholder="Enter email here"
            onChange={(event) => setEmail(event.target.value)}
            className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
            required />
        </p>
        {email}

        <p>
          <label className="block text-gray-700 text-sm font-bold mb-1" htmlFor="first_name">
            First Name:
          </label>
          <input 
            type="text" 
            placeholder="Enter your first name here" 
            onChange={(event)=>{setFName(event.target.value);}} 
            className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
            required/>
        </p>
        {fName}

        <p>
          <label className="block text-gray-700 text-sm font-bold mb-1" htmlFor="last_name">
            Last Name:
          </label>
          <input 
            type="text" 
            placeholder="Enter your last name here" 
            onChange={(event)=>{setLName(event.target.value);}} 
            className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
            required/>
        </p>
        {lName}

        <p>
          <label className="block text-gray-700 text-sm font-bold mb-1" htmlFor="phone_number">
            PhoneNumber:
          </label>
          <input 
            type="text" 
            placeholder="09xx-xxx-xxxx" 
            onChange={(event)=>{setPhoneNumber(event.target.value);}}
            className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
            required/>
        </p>
        {phoneNumber}
        <br />
        {errorMessage}
        <br />
        <button 
          type="submit" 
          className="w-full bg-blue-500 text-white font-bold py-2 rounded hover:bg-blue-600 transition duration-200">
            Submit</button>
      </form>
    </div>
  )
}

export default App

// Web Frameworks/Lab1-MangabatAster/lab1-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  email: string = "";
  firstName: string = "";
  lastName: string = "";
  phoneNumber: string = "";
  submitted: boolean = false;
  errorMessage: string = "";

  submitForm() {
    this.submitted = true;

    const validationMessage = this.formValid();
    const userData = {
      email: this.email,
      first_name: this.firstName,
      last_name: this.lastName,
      phone_number: this.phoneNumber
    };
    if (validationMessage == "") {
      console.log(userData);
      this.errorMessage = ""; 
    } else {
      this.errorMessage = validationMessage;
    }
  }

  formValid(): string {
    if (this.email == '' || this.firstName == '' || this.lastName == '' || this.phoneNumber == '') {
      return "Please fill out all fields.";
    }

    if (!this.numberValid()) {
      return "Please follow format: 09xx-xxx-xxxx.";
    }
    if(!this.emailValid()){
      return "Please enter a valid email."
    }
    return "";
  }

  numberValid(): boolean {
    const phoneRegex = /^09\d{2}-\d{3}-\d{4}$/;
    return phoneRegex.test(this.phoneNumber);
  }

  emailValid(): boolean{
    const emailRegex = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/;
    return emailRegex.test(this.email);
  }
}

<div class="flex items-center justify-center min-h-screen">
    <form class="w-full max-w-md p-8 rounded-lg border border-black">
      <h1 class="text-3xl font-extrabold text-center mb-6">Form</h1>
      <p class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-1" htmlFor="email">
          Email:
        </label>
        <input
          type="email"
          id="email"
          [(ngModel)]="email"
          name="email"
          placeholder="Enter email here"
          class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
          required />
      </p>
      {{email}}
    
      <p>
        <label class="block text-gray-700 text-sm font-bold mb-1" htmlFor="first_name">
          First Name:
        </label>
        <input 
          type="text" 
          placeholder="Enter your first name here" 
          [(ngModel)]="firstName"
          name="firstName"
          class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
          required/>
      </p>
      {{firstName}}
    
      <p>
        <label class="block text-gray-700 text-sm font-bold mb-1" htmlFor="last_name">
          Last Name:
        </label>
        <input 
          type="text" 
          placeholder="Enter your last name here" 
          [(ngModel)]="lastName"
          name="lastName"
          class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
          required/>
      </p>
      {{lastName}}
    
      <p>
        <label class="block text-gray-700 text-sm font-bold mb-1" htmlFor="phone_number">
          PhoneNumber:
        </label>
        <input 
          type="text" 
          placeholder="09xx-xxx-xxxx" 
          [(ngModel)]="phoneNumber"
          name="phoneNumber"
          class="w-full px-3 py-2 border border-gray-300 rounded focus:outline-blue-700"
          required/>
      </p>
      {{phoneNumber}}
      <br>
      {{errorMessage}}
      <br>
    
      <button 
        type="submit"
        (click)="submitForm()"
        class="w-full bg-blue-500 text-white font-bold py-2 rounded hover:bg-blue-600 transition duration-200">
        Submit</button>
    </form>
  </div>
